# Author Cristo
version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env
    networks:
      - gaming-network
    container_name: database
  django:
    build: 
      context: .
      dockerfile: Dockerfile.prd
    command: gunicorn gaming.wsgi --bind 0.0.0.0:8000
    volumes:
      - .:/home/app/gaming/
      - static_volume:/home/app/gaming/staticfiles
      - media_volume:/home/app/gaming/mediafiles
    expose:
      - 8000
    env_file:
      - ./env/django.env
    networks:
      - gaming-network
    container_name: django
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    networks:
      - gaming-network
    depends_on:
      - django
    volumes:
      - ./certs:/etc/nginx/certs
      - static_volume:/home/app/gaming/staticfiles
      - media_volume:/home/app/gaming/mediafiles
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    container_name: nginx
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    container_name: certbot
    
    

volumes:
  dbdata:
  static_volume:
  media_volume:

networks:
  gaming-network: