# Author Cristo
version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env
    networks:
      - gaming-network
    container_name: database
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/gaming
    ports:
      - 8000:8000
    env_file:
      - ./env/django.env
    networks:
      - gaming-network
    container_name: django
    depends_on:
      - db
    

volumes:
  dbdata:

networks:
  gaming-network: