# Author Cristo
#this file is prod only
version: "3.9"

services:
  db:
    restart: always
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env
    networks:
      - gaming-network
    container_name: database
  django:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.prd
    command: gunicorn gaming.wsgi --bind 0.0.0.0:8000
    volumes:
      - .:/home/app/gaming/
      - static_volume:/home/app/gaming/staticfiles
      - media_volume:/home/app/gaming/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./env/django.env
    networks:
      - gaming-network
    container_name: django
    depends_on:
      - db
  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - gaming-network
    depends_on:
      - django
    volumes:
      - ./certs:/etc/nginx/certs
      - static_volume:/home/app/gaming/staticfiles
      - media_volume:/home/app/gaming/mediafiles
      # - /etc/letsencrypt/live/cidesports.com/:/etc/letsencrypt/live/cidesports.com/
    container_name: nginx
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw
  #   container_name: certbot
    
    

volumes:
  dbdata:
  static_volume:
  media_volume:
  letsencrypt:

networks:
  gaming-network: