# Author Cristo
version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env
    networks:
      - gaming-network
    container_name: database
  nginx:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    network: host
    container_name: nginx
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/gaming
    ports:
      - "8000:8000"
    env_file:
      - ./env/django.env
    networks:
      - gaming-network
    container_name: django
    depends_on:
      - db
    

volumes:
  dbdata:

networks:
  gaming-network: